version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pg_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: factory_ci
      POSTGRES_PORT: 5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    networks:
      - pg_network
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LIST_PORT: 80

volumes:
  postgres_data:

networks:
  pg_network:
    driver: bridge
